feat(scripts/generate-secrets): more verbose messaging when secrets are generated

diff --git a/scripts/generate-secrets b/scripts/generate-secrets
--- a/scripts/generate-secrets
+++ b/scripts/generate-secrets
@@ -1,6 +1,11 @@
 #! /usr/bin/env bash
 set -e
 
+# Colours
+red='\033[0;31m'
+green='\033[0;32m'
+reset='\033[0m'
+
 influx_key_env=".env.influxdb"
 secret_key_env=".env.secret_key"
 public_key_env=".env.public_key"
@@ -36,6 +41,21 @@ fi
 
 if [[ -z "${PLACE_SERVER_SECRET}" || -z "${JWT_PUBLIC}" || -z "${JWT_SECRET}" ]]; then
   dir=$(mktemp -d)
+
+  if [[ -n "${PLACE_SERVER_SECRET}"  ]]; then
+      echo "${red}ERROR${reset}: the ${secret_key_env} file contains an existing secret."
+      echo "Please update the file should look like the following..."
+      echo "JWT_SECRET=<existing-instance-secret>"
+      echo "SECRET_KEY_BASE=<existing-instance-secret>"
+      echo "PLACE_SERVER_SECRET=<existing-instance-secret>"
+      echo "SERVER_SECRET=<existing-instance-secret>"
+      exit 1
+  elif [[ -n "${JWT_SECRET}" && -z "${PLACE_SERVER_SECRET}" ]]
+      echo "${red}ERROR${reset}: this instance has previously been initialised with a default secret"
+      echo "Please contact support@place.technology"
+      exit 1
+  fi
+
 
   ssh-keygen -t rsa -b 4096 -m PEM -f "${dir}/secret" -N "" &>/dev/null
   openssl rsa -in "${dir}/secret" -pubout -outform PEM -out "${dir}/public" 0>&- &>/dev/null
