fix: unify instance secrets (#50)
* fix: unify instance secret

* feat(scripts/generate-secrets): more verbose messaging when secrets are generated

* docs(scripts/generate-secrets): include extra context

diff --git a/scripts/generate-secrets b/scripts/generate-secrets
--- a/scripts/generate-secrets
+++ b/scripts/generate-secrets
@@ -1,17 +1,18 @@
 #! /usr/bin/env bash
 set -e
 
+# Colours
+red='\033[0;31m'
+green='\033[0;32m'
+reset='\033[0m'
+
 influx_key_env=".env.influxdb"
 secret_key_env=".env.secret_key"
 public_key_env=".env.public_key"
-server_secret_env=".env.server_secret"
 instance_telemetry_key_env=".env.instance_telemetry_key"
 env=".env"
 
 set -a
-if [[ -f "${server_secret_env}" ]]; then
-  . ${server_secret_env}
-fi
 if [[ -f "${influx_key_env}" ]]; then
   . ${influx_key_env}
 fi
@@ -38,26 +39,53 @@ else
   echo "already generated INFLUX_API_KEY"
 fi
 
-if [[ -z "${JWT_PUBLIC}" || -z "${JWT_SECRET}" ]]; then
+if [[ -z "${PLACE_SERVER_SECRET}" || -z "${JWT_PUBLIC}" || -z "${JWT_SECRET}" ]]; then
   dir=$(mktemp -d)
+
+  if [[ -n "${PLACE_SERVER_SECRET}"  ]]; then
+      echo "${red}ERROR${reset}: the ${secret_key_env} file contains an existing secret."
+      echo "Please update the file should look like the following..."
+      echo "JWT_SECRET=<existing-instance-secret>"
+      echo "SECRET_KEY_BASE=<existing-instance-secret>"
+      echo "PLACE_SERVER_SECRET=<existing-instance-secret>"
+      echo "SERVER_SECRET=<existing-instance-secret>"
+      exit 1
+  elif [[ -n "${JWT_SECRET}" && -z "${PLACE_SERVER_SECRET}" ]]
+      echo "${red}ERROR${reset}: this instance has previously been initialised with a default secret."
+      echo "See the ${green}server:rotate_server_secret${reset} task here https://github.com/PlaceOS/init#scripts"
+      echo "Please contact support@place.technology if you need help."
+      exit 1
+  fi
+
 
   ssh-keygen -t rsa -b 4096 -m PEM -f "${dir}/secret" -N "" &>/dev/null
   openssl rsa -in "${dir}/secret" -pubout -outform PEM -out "${dir}/public" 0>&- &>/dev/null
 
   secret="$(base64 -w 0 -i "${dir}/secret")"
-  secret_env_key="JWT_SECRET=${secret}"
-  server_secret_env_key="SECRET_KEY_BASE=${secret}"
-  echo ${secret_env_key} >$secret_key_env
+
+  # JWT secret
+  jwt_secret_env_key="JWT_SECRET=${secret}"
+
+  # Used in Rails
+  secret_key_base_env_key="SECRET_KEY_BASE=${secret}"
+
+  # Used in PlaceOS
+  place_server_secret_env_key="PLACE_SERVER_SECRET=${secret}"
+  server_secret_env_key="SERVER_SECRET=${secret}"
+
+  echo ${jwt_secret_env_key} >$secret_key_env
+  echo ${secret_key_base_env_key} >>$secret_key_env
   echo ${server_secret_env_key} >>$secret_key_env
+  echo ${place_server_secret_env_key} >>$secret_key_env
 
   public_env_key="JWT_PUBLIC=$(base64 -w 0 -i "${dir}/public")"
   echo $public_env_key >$public_key_env
 
-  echo "generated JWT_SECRET and JWT_PUBLIC"
+  echo "generated PLACE_SERVER_SECRET, JWT_SECRET and JWT_PUBLIC"
 
   rm -r "${dir}"
 else
-  echo "already generated JWT_SECRET and JWT_PUBLIC"
+  echo "already generated PLACE_SERVER_SECRET, JWT_SECRET and JWT_PUBLIC"
 fi
 
 if [[ ! -f .htpasswd-kibana ]]; then
@@ -65,14 +93,6 @@ if [[ ! -f .htpasswd-kibana ]]; then
   echo "generated kibana basic auth"
 else
   echo "already generated kibana basic auth"
-fi
-
-if [[ -z "${PLACE_SERVER_SECRET}" ]]; then
-  PLACE_SERVER_SECRET="$(LOG_LEVEL=none task create:instance_key)"
-  echo "PLACE_SERVER_SECRET=${PLACE_SERVER_SECRET}" >"$server_secret_env"
-  echo "generated PLACE_SERVER_SECRET"
-else
-  echo "already generated PLACE_SERVER_SECRET"
 fi
 
 if [[ -z "${PLACE_INSTANCE_TELEMETRY_KEY}" ]]; then
